version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    environment:
      - MONGO_URI=mongodb://mongo:27017/tryage_db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - mongo
    volumes:
      - ./src:/app/src # Hot reload for development
      - ./src/static:/app/src/static
    networks:
      - tryage-network

  api:
    build: .
    entrypoint: [ "uvicorn", "src.api.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/tryage_db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - mongo
    volumes:
      - ./src:/app/src
    networks:
      - tryage-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - web
    networks:
      - tryage-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - tryage-network

volumes:
  mongo_data:


networks:
  tryage-network:
    driver: bridge
